CREATE TABLE IF NOT EXISTS `admin_trades` (
  `trade_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '取引ID',
  `related_trade_id` int(11) NOT NULL COMMENT '関連取引ID',
  `trade_name` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT '取引名称',
  `trade_type_id` int(11) NOT NULL COMMENT '取引種別ID',
  `worker_operator_id` int(11) NOT NULL COMMENT '受注担当者ID',
  `customer_operator_id` int(11) NOT NULL COMMENT '発注担当者ID',
  `price_rate` int(11) NOT NULL COMMENT '案件全体に対する金額の比率',
  `subtotal` int(11) NOT NULL COMMENT '小計',
  `discount` int(11) NOT NULL COMMENT '割引金額',
  `tax` int(11) NOT NULL COMMENT '消費税',
  `total` int(11) NOT NULL COMMENT '合計金額',
  `start_date` date NOT NULL COMMENT '見積書発行日',
  `planed_date` date NOT NULL COMMENT '見積書発行日',
  `ordered_date` date NOT NULL COMMENT '発注書発行日',
  `delivered_date` date NOT NULL COMMENT '納品日',
  `billing_date` date NOT NULL COMMENT '請求書発行日',
  `payment_date` date NOT NULL COMMENT '支払い期限日',
  `complete_date` date NOT NULL COMMENT '入金確認日',
  `trade_status_id` int(11) NOT NULL COMMENT '取引ステータス',
  `continue_interval` int(1) NOT NULL COMMENT '継続案件発行間隔月数',
  `description` varchar(8192) COLLATE utf8_unicode_ci NOT NULL COMMENT '特記事項',
  `comment` varchar(8192) COLLATE utf8_unicode_ci NOT NULL COMMENT '備考',
  `create_time` datetime NOT NULL COMMENT 'データ登録日時',
  `update_time` datetime NOT NULL COMMENT 'データ最終更新日時',
  PRIMARY KEY (`trade_id`),
  KEY `related_trade_id` (`related_trade_id`),
  KEY `worker_operator_id` (`worker_operator_id`),
  KEY `customer_operator_id` (`customer_operator_id`),
  KEY `trade_type_id` (`trade_type_id`),
  KEY `trade_status_id` (`trade_status_id`),
  KEY `start_date` (`start_date`),
  KEY `ordered_date` (`ordered_date`),
  KEY `planed_date` (`planed_date`),
  KEY `delivered_date` (`delivered_date`),
  KEY `billing_date` (`billing_date`),
  KEY `payment_date` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='管理組織取引テーブル';

ALTER TABLE `admin_trades`
  ADD CONSTRAINT `admin_trades_ibfk_4` FOREIGN KEY (`trade_status_id`) REFERENCES `admin_trade_statuses` (`trade_status_id`),
  ADD CONSTRAINT `admin_trades_ibfk_1` FOREIGN KEY (`trade_type_id`) REFERENCES `admin_trade_types` (`trade_type_id`),
  ADD CONSTRAINT `admin_trades_ibfk_2` FOREIGN KEY (`worker_operator_id`) REFERENCES `admin_company_operators` (`operator_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `admin_trades_ibfk_3` FOREIGN KEY (`customer_operator_id`) REFERENCES `admin_company_operators` (`operator_id`) ON DELETE CASCADE ON UPDATE CASCADE;
